apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: feed
  name: feed
spec:
  replicas: 1
  selector: 
    matchLabels: 
      app: feed
  template:
    metadata:
      labels:
        app: feed
        service: feed
    spec:
      containers:
      - image: rochanajayakumar/udagram:feed
        name: feed
        imagePullPolicy: Always          
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "1024Mi"
            cpu: "500m"       
        ports:
        - containerPort: 8080
      restartPolicy: Always
