language: node_js
node_js:
  - 12

services:
  - docker

# Pre-testing installs
install:
  - echo "nothing needs to be installed"

# Scripts to be run such as tests
before_script:
  - echo "no tests"

script:
  - docker --version # print the version for logging
  - docker --version # print the version for logging
  - docker build -t udagram-feed udagram-api-feed/
  - docker build -t udagram-user udagram-api-users/
  - docker build -t udagram-front udagram-frontend/
  - docker tag udagram-feed rochanajayakumar/udagram/udagram-feed:feed
  - docker tag udagram-user rochanajayakumar/udagram/udagram-user:user
  - docker tag udagram-front rochanajayakumar/udagram/udagram-front:front

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push rochanajayakumar/udagram/udagram-feed
  - docker push rochanajayakumar/udagram/udagram-user
  - docker push rochanajayakumar/udagram/udagram-front

