language: node_js
node_js:
  - 12

services:
  - docker

# Pre-testing installs
install:
  - echo "nothing needs to be installed"

# Scripts to be run such as tests
before_script:
  - echo "no tests"

script:
  - docker --version # print the version for logging
  - docker --version # print the version for logging
  - docker build -t udagram udagram-api-feed/
  - docker build -t udagram udagram-api-users/
  - docker build -t udagram udagram-frontend/
  - docker build -t udagram udagram-reverse/
  - docker tag udagram rochanajayakumar/udagram:feed
  - docker tag udagram rochanajayakumar/udagram:user
  - docker tag udagram rochanajayakumar/udagram:front
  - docker tag udagram rochanajayakumar/udagram:reverse 

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push rochanajayakumar/udagram:feed
  - docker push rochanajayakumar/udagram:user
  - docker push rochanajayakumar/udagram:front
  - docker push rochanajayakumar/udagram:reverse

