apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: users
  name: users
spec:
  replicas: 1
  selector: 
    matchLabels: 
      app: users
  template:
    metadata:
      labels:
        app: users
        service: users
    spec:
      containers:
      - image: rochanajayakumar/udagram:users
        name: users
        imagePullPolicy: Always          
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "1024Mi"
            cpu: "500m"       
        ports:
        - containerPort: 8080
      restartPolicy: Always
