apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: api
  name: api
spec:
  replicas: 1
  selector: 
    matchLabels: 
      app: api
  template:
    metadata:
      labels:
        app: api
        service: api
    spec:
      containers:
      - image: rochanajayakumar/udagram:api
        name: api
        imagePullPolicy: Always          
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "1024Mi"
            cpu: "500m"       
        ports:
        - containerPort: 8080
      restartPolicy: Always
